source 'http://rubygems.org'

gem 'rails', '4.2.1'

gem 'rails-api'

gem 'spring', :group => :development

gem 'pg'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Make any Ruby object quack like ActiveRecord
gem 'active_type', '~> 0.4.0'
#---
# Backported from Rails 5.0 to use with 4.x versions
gem 'active_model-errors_details', '~> 1.1.1'

#Builds a tree of errors instead of the 1-dimension one generated by ActiveMode::Base#errors.messages.
gem 'activemodel-errors-tree', '~> 0.1.0'

# JSON Web Token implementation in Ruby
gem 'jwt', '~> 1.5.1'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
